### ISSUE TITLE
Image Attachment not shown in UITextView with attributed string

### ISSUE THREAD

**Issue by uuttff8** [gonzalezreal/MarkdownUI#36]
as title says, UITextView doesn't show images 

here is example with images and UITextView

https://drive.google.com/drive/folders/1rwlJSGCEKnzW1biN6FCcjsrnNqH66S_3?usp=sharing

Please, correct me if I am wrong. Or suggest libraries that will show correct UITextView with images.

**Comment by uuttff8** [comment]
And also, I can't use SwiftUI because of ios 12 support.

**Comment by gonzalezreal** [comment]
Hi @uuttff8,

This is the expected behaviour. Notice that the `NSAttributedString` extension does not load images asynchronously. Instead, it provides an optional `attachments` parameter that you can use to associate existing text attachments with image URL strings.

https://github.com/gonzalezreal/MarkdownUI/blob/079e08576d506fbc42184f175b2ca8a898da9a30/Sources/MarkdownUI/Shared/NSAttributedString%2BMarkdown.swift#L14
